name: Improve existing content
description: Make a suggestion to improve the content on an existing page.
labels:
  - documentation
body:
  - type: markdown
    attributes:
      value: |
        * Before submitting an issue, read the [Contribution guide](https://docs.roninchain.com/docs/community/contribute/guide).
        * Check if someone hasn't already opened a similar [issue](https://github.com/axieinfinity/ronin-documentation/issues).

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: This project has a Code of Conduct that all contributors are expected to follow.
      options:
        - label: I've read and agree to the Ronin documentation project's [Code of Conduct](https://github.com/axieinfinity/ronin-documentation/blob/main/CODE_OF_CONDUCT.md)
          required: true

  - type: textarea
    attributes:
      label: What page on docs.roninchain.com is affected?
      description: Link to the page you'd like to see updated.
    validations:
      required: true

  - type: textarea
    attributes:
      label: What parts of the page would you like to see updated?
      description: |
        - Give as much detail as you can to help us understand the change you want to see. 
        - Why should the docs be changed? What use cases does the change support? 
        - What is the expected outcome?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional information
      description: Add any other context or screenshots about the change request here.
    validations:
      required: false
